In [1]:
import numpy as np

In [2]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

# Implement Mean Absolute Error


In [3]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [4]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


0.5

Implement same thing using numpy in much easier way



In [5]:
np.abs(y_predicted-y_true)


array([0.7, 0.3, 1. , 0. , 0.5])

In [6]:
np.mean(np.abs(y_predicted-y_true))


0.5

In [7]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [8]:
mae_np(y_predicted, y_true)


0.5

# Implement Log Loss or Binary Cross Entropy



In [9]:
np.log([0])


C:\Users\IDEH\AppData\Local\Temp\ipykernel_10892\348854998.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [10]:
epsilon = 1e-15


In [11]:
np.log([1e-15])


array([-34.53877639])

In [12]:
y_predicted

array([1, 1, 0, 0, 1])

In [13]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [14]:
y_predicted_new = np.array(y_predicted_new)


In [16]:
np.log(y_predicted_new)


array([  0.        ,   0.        , -34.53877639, -34.53877639,
         0.        ])

In [17]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))


C:\Users\IDEH\AppData\Local\Temp\ipykernel_10892\3393954814.py:1: RuntimeWarning: divide by zero encountered in log
  -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))


inf

In [18]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))
log_loss(y_true, y_predicted)

17.2696280766844